#!/usr/bin/env python3


# Requirement
# pip install rich


import argparse
import os
from xml.etree import ElementTree as ET
from rich.tree import Tree
from rich.console import Console


def build_tree(element, parent_tree):
    node_label = f"[bold]{element.tag}[/]"
    if element.attrib:
        attributes = " ".join([f"{key}='{value}'" for key, value in element.attrib.items()])
        node_label += f" [dim](Attributes: {attributes})[/]"

    current_tree = parent_tree.add(node_label)

    for child in element:
        build_tree(child, current_tree)

    if element.text and element.text.strip():
        current_tree.add(f"[italic dim]{element.text.strip()}[/]")


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Print xml tree.")
    parser.add_argument("file_path", type=str, help="Path to the input xml file.")
    args = parser.parse_args()
    file_path = args.file_path
    file_name = os.path.basename(file_path)

    root = ET.parse(file_path).getroot()

    tree = Tree(f"[bold green]{file_name}[/]")
    build_tree(root, tree)

    console = Console()
    console.print(tree)
