#!/usr/bin/env python3


# https://pypi.org/project/yaml2dot/
# pip install yaml2dot

# https://pypi.org/project/graphviz/
# pip install graphviz


import argparse
from yaml2dot import data_loader, converter
from graphviz import Source


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Convert yml to svg.")

    parser.add_argument("-i", "--input", required=True, type=str, help="Path to the input dot file.")
    parser.add_argument("-o", "--output", required=True, type=str, help="Path to the output svg file." )

    args = parser.parse_args()

    data = data_loader.load_yaml_or_json(args.input)

    dot_text = converter.convert_yaml_or_json_to_format(data, output_format="dot")    

    try:
        graph = Source(dot_text)
        graph.render(outfile=args.output, format="svg", cleanup=True)

    except Exception as e:
        print(f"Error: {e}")