#!/usr/bin/env python3


# Requirement
# pip install yaml rich


import argparse
import os
import yaml
from rich.console import Console
from rich.tree import Tree


def build_tree(data, parent=None):
    if isinstance(data, dict):
        for key, value in data.items():
            child = parent.add(f"[bold]{key}[/]")
            build_tree(value, child)
    elif isinstance(data, list):
        for i, item in enumerate(data):
            child = parent.add(f"[bold][{i}][/]")
            build_tree(item, child)
    else:
        parent.add(f"[italic dim]{data}[/]")

    return parent


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Convert yml to svg.")
    parser.add_argument("-i", "--input", required=True, type=str, help="Path to the input yml file.")
    args = parser.parse_args()
    file_path = args.input
    file_name = os.path.basename(file_path)

    file = open(file_path, "r")
    
    data = yaml.safe_load(file)

    root = Tree(f"[bold green]{file_name}[/]")
    tree = build_tree(data, root)
    
    console = Console()
    console.print(tree)
